# Generated by Django 3.1.1 on 2020-09-21 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='match_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=255)),
                ('selected_column', models.IntegerField()),
                ('game_assoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.gameinfo')),
            ],
        ),
    ]
